"""Added email column to User table

Revision ID: 6a0a3663579a
Revises: 
Create Date: 2024-12-02 17:33:55.694294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a0a3663579a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('firstName', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('lastName', sa.String(length=50), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('lastName')
        batch_op.drop_column('firstName')
        batch_op.drop_column('email')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
