"""Added password_hash column to User table

Revision ID: 78657fdc48e1
Revises: 6a0a3663579a
Create Date: 2024-12-02 17:39:18.750739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78657fdc48e1'
down_revision = '6a0a3663579a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
